---
title: "kdx2020"
author: "JustY"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) # 데이터 가공 및 시각화
library(readxl) # 엑셀파일 불러오기 패키지
```

```{r}
category_list <- cat_rev$카테고리명
category_list

i = 1
j = i+7
category_list <- as.character(category_list)

cat_rev2 %>% 
  filter(카테고리명 %in% category_list[c(i:as.numeric(i+7))]) %>% 
  ggplot(aes(x = 카테고리명, y = mean, fill = 고객성별)) +
  geom_bar(stat="identity", position = "dodge", width=.5) + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
  labs(title="Ordered Bar Chart", 
       subtitle="카테고리명 Vs Avg. 구매금액 by 고객성별", 
       caption="source: products")

category_graph <- function(df, cat_list = cat_list) {
  category_list <- sort(as.character(cat_list))
  
  print(category_list)
  for (i in seq(1, 64, by = 8)) {
    i = i
    j = i+7
    plot <- df %>% 
      filter(카테고리명 %in% category_list[i:j]) %>% 
      ggplot(aes(x = 카테고리명, y = mean, fill = 고객성별)) +
      geom_bar(stat="identity", position = "dodge", width=.5) + 
      theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
      labs(title="Ordered Bar Chart", 
           subtitle="카테고리명 Vs Avg. 구매금액 by 고객성별", 
           caption="source: products")
    
    print(plot)
  }
}

category_graph(cat_rev2, category_list)
```


