---
title: "3장 데이터 변형"
author: "ruleover"
date: '2020 9 29 '
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
library(gapminder)
library(Lahman)
```

## 3장 데이터 변형

### 3.2 filter()로 행 필터링하기

#### 3.2.4 연습문제

1. 다음 조건을 만족하는 항공편을 모두 찾아라.

```{r}
# a. 2시간 이상 도착 지연.
filter(flights, arr_delay >= 120)

# b. 휴스턴(IAH 혹은 HOU)으로 운항.
filter(flights, dest == "IAH" | dest == "HOU")

# c. 유나이티드항공(United), 아메리칸항공(American), 델타항공(Delta)이 운항.
airlines
filter(flights, carrier %in% c("AA", "DL", "UA"))

# d. 여름(7,8,9월)에 출발.
filter(flights, month >= 7, month <= 9)
# filter(flights, month %in% 7:9)
# filter(flights, month == 7 | month == 8 | month == 9)

# e. 2시간 이상 지연 도착했지만, 지연 출발하지는 않음.
filter(flights, arr_delay > 120, dep_delay <= 0)

# f. 최소 한 시간 이상 지연 출발했지만 운항 중 30분 이상 단축.
filter(flights, dep_delay >= 60, dep_delay - arr_delay > 30)

# g. 자정과 6am(포함) 사이에 출발.
summary(flights$dep_time)
filter(flights, dep_time <= 600 | dep_time == 2400)
# c(600, 1200, 2400) %% 2400
# [1]  600 1200    0
filter(flights, dep_time %% 2400 <= 600)
```

2. 





